analyzer:
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    unrelated_type_equality_checks: ignore
    strict_top_level_inference: ignore
include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
